name: "Change-detection_builder"
description: "Change-detection_builder"

inputs:
  exclude_paths:
    description: '"Path to exclude while running change detection.'
    type: string
    default: '.yaml, .yml, .github/'
    
outputs:
  changed_modules:
    description: "Path of modules which got changed"
    value: ${{ steps.python_script.outputs.changed_modules_path }}

runs:
  using: "composite"
  steps:
  
    - name: Git configuration
      run: git config --global --add safe.directory '*'
      shell: bash  

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42
    
    - name: Python command
      id: python_script
      run: |
        echo "${{ steps.changes.outputs.all }}"
        python3 ${GITHUB_ACTION_PATH}/maven.py \
          "${{ steps.changed-files.outputs.all_changed_files }}" \
          "${GITHUB_WORKSPACE}" \
          "${{ inputs.exclude_paths }}"
      shell: bash
