name: "Change-detection_builder"
description: "Change-detection_builder"

outputs:
  changed_modules:
    description: "Names of modules which got changed"
    value: ${{ steps.python_script.outputs.changed_modules }}
  changed_modules_path:
    description: "Path of modules which got changed"
    value: ${{ steps.python_script.outputs.changed_modules_path }}

runs:
  using: "composite"
  steps:
  
    - name: Git configuration
      run: git config --global --add safe.directory '*'
      shell: bash  

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v37
    
    - name: Python command
      id: python_script
      run: |
        echo "${{ steps.changes.outputs.all }}"
        python3 ${GITHUB_ACTION_PATH}/maven.py \
          "${{ steps.changed-files.outputs.all_changed_files }}" \
          "${GITHUB_WORKSPACE}" 
      shell: bash