name: "Change Detection"
description: "Change Detection for modules"

inputs:
  project_type:
    description: "The project type. Maven Etc"
    required: true

runs:
  using: "composite"
  steps:
  
    - name: Python setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 

    - name: Git configuration
      run: git config --global --add safe.directory '*'
      shell: bash  
      
    - name: Get changed files
      id: changes
      shell: bash
        run: |
          changes=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)
          echo "all=${changes}" >> $GITHUB_OUTPUT

    - run: |
        python3 ${GITHUB_ACTION_PATH}/maven.py \
          "${GITHUB_WORKSPACE}" \
          "${{ inputs.project_type }}"